### ISSUE TITLE
Not building from tar (version issue)

### ISSUE THREAD

**Issue by piskorzj** [jp-embedded/scxmlcc#100]
Probably related to #56 

I can't build scxmlcc using tar package. It is failing on `Generating ../version_auto.h`.

Steps to reproduce:

```
wget https://github.com/jp-embedded/scxmlcc/archive/0.9.tar.gz
tar axf 0.9.tar.gz
mkdir build && cd build
cmake ../scxmlcc-0.9
make
```

Output:
```
$ make
[ 16%] Generating ../version_auto.h
error: No repo or cache detected.
src/CMakeFiles/scxmlcc.dir/build.make:61: recipe for target 'version_auto.h' failed
make[2]: *** [version_auto.h] Error 1
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/scxmlcc.dir/all' failed
make[1]: *** [src/CMakeFiles/scxmlcc.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

Tested on ubutnu 16.04 and 18.04.

**Comment by jp-embedded** [comment]
Thanks for the observation. Will look into it.

**Comment by jp-embedded** [comment]
fixed in pull request #101 
Will close issue when a new tagged release is ready

**Comment by jp-embedded** [comment]
I think there will be a new tagged release in week 28, so this can be closed

**Comment by piskorzj** [comment]
Nice, I've tested it with downloading master (`wget https://github.com/jp-embedded/scxmlcc/archive/master.tar.gz`) and now it compiles fine.
