### ISSUE TITLE
is the fsm thread safe?can i run it in multiple thread safety

### ISSUE THREAD

**Issue by hanhao44** [jp-embedded/scxmlcc#109]
is the fsm thread safe?can i run it in multiple thread safety

**Comment by hanhao44** [comment]
class CEca_strategy_state_machine1
{
public:
	void dispatch(sc_h::event e = &sc_h::state::unconditional);
public:
	sc_h::user_model um;
	sc_h sc;
};

can i safety create the class in muiltiple thread.

**Comment by jp-embedded** [comment]
There is an option '--threadsafe' to scxmlcc which makes it generate thread safe code.

**Comment by hanhao44** [comment]
thanks,very much
