### ISSUE TITLE
Version is bad

### ISSUE THREAD

**Issue by Bktero** [jp-embedded/scxmlcc#47]
Hello,

version.h contains 0.8.3 in both master/head and tag for version 0.8.5. I guess this is obviously wrong ;)

Best regards,
Bktero

**Comment by jp-embedded** [comment]
Thanks. That's an error. I will get this fixed

**Comment by Bktero** [comment]
This issue is now fixed: https://github.com/jp-embedded/scxmlcc/commit/4f96b927cb1bc4bf993c621394b97ffe869bbc96
