### ISSUE TITLE
GCC warns about extra ;

### ISSUE THREAD

**Issue by Bktero** [jp-embedded/scxmlcc#48]
Hello,

In [cpp_output.cpp](https://github.com/jp-embedded/scxmlcc/blob/master/src/cpp_output.cpp), there is the following code (line 887):

	// new_state
	out << tab << "template<class T> T* new_state()" << endl;
	out << tab << '{' << endl;
	out << tab << tab << "static T t;" << endl;
	out << tab << tab << "return &t;" << endl;
	out << tab << "};" << endl;

	out << "};" << endl;
	out << endl;

The last **;** is not necessary. GCC warns about this extra **;** if the -Wpedantic option is used.
Is there any good reason not to remove it?

Best regards,
Bktero

**Comment by ringlej** [comment]
The extra `;` is not the last one that you show in the snippet you are quoting, but rather the one before that that is tacked on to the end of the template function `new_state()`

**Comment by jp-embedded** [comment]
Thanks. It's an error. It can be removed.

**Comment by Bktero** [comment]
Sorry I have copied to much code... You're right I am talking about the extra ; at the end of the template function `new_state()`.

**Comment by Bktero** [comment]
Here it is https://github.com/jp-embedded/scxmlcc/pull/49
