### ISSUE TITLE
Building the project

### ISSUE THREAD

**Issue by mahmudemam** [jp-embedded/scxmlcc#5]
Hello,

I've downloaded the project and all of the required libraries, but when I tried to build it I got the following errors:

autorevision -tsh > autorevision.mk && sh makerevision.sh || truncate -s0 autorevision_postfix.h
warning: Counting the number of revisions may be slower due to an outdated git version less than 1.7.2.3. If something breaks, please update it.
g++  -Wall -O2 -MD -MP  -c -o main.o main.cpp
main.cpp: In function ‘void scxmlcc(const options&)’:
main.cpp:41: error: ‘struct std::basic_string<char, std::char_traits<char>, std::allocator<char> >’ has no member named ‘string’
main.cpp:44: error: ‘const struct boost::filesystem::path’ has no member named ‘c_str’
main.cpp: In function ‘int main(int, char**)’:
main.cpp:69: error: ‘cerr’ was not declared in this scope
main.cpp:86: error: ‘cout’ was not declared in this scope
main.cpp:108: error: ‘cout’ was not declared in this scope
main.cpp:117: error: ‘cerr’ was not declared in this scope
make: *** [main.o] Error 1

**Comment by jp-embedded** [comment]
Hi 

Thanks for your build report.

Can you tell my which system you are building on. Then I will look into it.
Have you checked out the master branch via git, or?

**Comment by mahmudemam** [comment]
Yes, I've cloned the repo from github, also I'm building it on CentOS 6.6.

**Comment by jp-embedded** [comment]
Fixed in 0.4.3

**Comment by mahmudemam** [comment]
Thanks for caring.

Some of issues have been solved, but I still facing the following:

autorevision -tsh > autorevision.mk && sh makerevision.sh || truncate -s0 autorevision_postfix.h
warning: Counting the number of revisions may be slower due to an outdated git version less than 1.7.2.3. If something breaks, please update it.
diff: autorevision_postfix.h: No such file or directory
g++  -Wall -O2 -MD -MP  -c -o main.o main.cpp
main.cpp: In function ‘void scxmlcc(const options&)’:
main.cpp:42: error: ‘struct std::basic_string<char, std::char_traits<char>, std::allocator<char> >’ has no member named ‘string’
main.cpp:45: error: ‘const struct boost::filesystem::path’ has no member named ‘c_str’

It seems that string not included or something like that?

**Comment by jp-embedded** [comment]
Thanks for your input
I have reproduced and fixed the build error on CentOS 6.7
Fixed in 0.4.4

**Comment by mahmudemam** [comment]
Hello, 
Sorry for being late, also the fix now is working well.

**Comment by jp-embedded** [comment]
Good to know :-). Any feedback is welcome. Pros, cons, did you end up using it, etc.
