### ISSUE TITLE
scxmlcc fails with error: parse_log: No such node (<xmlattr>)

### ISSUE THREAD

**Issue by mcirsta** [jp-embedded/scxmlcc#62]
I've tried compiling the attached file that was created with the QtCreator editor and got the following error:

error: parse_log: No such node (<xmlattr>)

 It's not really clear to me if this is an unsupported attribute , a bug , or if the file generated but QtCreator is invalid.

[door.scxml.zip](https://github.com/jp-embedded/scxmlcc/files/2072960/door.scxml.zip)

**Comment by mcirsta** [comment]
In the meantime I found that the error is caused by the empty  <log></log> present in the file.
 While exactly QtCreator added this I don't know but I think it should not be that hard to handle this one.

**Comment by jp-embedded** [comment]
"the empty preset"?

Can you describe which part of the file you mean?

**Comment by jp-embedded** [comment]
fixed in 0dccbfce8ca29e4ad30ef46c5d85013516145abb
