### ISSUE TITLE
datamodel does not support custom structures "natively" (but some workaround is available)

### ISSUE THREAD

**Issue by valioiv** [jp-embedded/scxmlcc#63]
It seems impossible to put your own type for the <data> entries - float, std::vector, some custom structure (#include "custom_struct.h" prior to), etc.
Data in SCXML like that:

```xml
  <!--  trivial 5 second microwave oven example -->
  <datamodel>
    <data id="cook_time" expr="5"/>
    <data id="door_closed" expr="true"/>
    <data id="timer" expr="0"/>
  </datamodel>
```

produce the following snippet:

```cpp
//...
  int cook_time;
  int door_closed;
  int timer;
  data_model() : cook_time(5), door_closed(true), timer(0) {}
//...
```

Is it known to fixing it or how to workaround it in a different way?

**For example if have something like that:**

```xml
  <!--  trivial 5 second microwave oven example -->
  <datamodel>
    <data id="CustomStruct1 cust" expr=""/>
    <data id="float flt" expr="0.5"/>
  </datamodel>
```

how the output will become (or anything compilable close to):

```cpp
//...
  #include "<path_to_my_custom_header.h>"
  CustomStruct1 cust;
  float flt;
  data_model() : cust(), flt(0.5) {}
//...
```

**Comment by jp-embedded** [comment]
well, your example should work already exactly as is ;-)
except for the inclusion of custom types. The include part is not supported yet, but I will try if I can priorotize that.

An obvious workaround is to include the files before you include your state machine.

The documentation regarding this is also missing.

**Comment by valioiv** [comment]
Yep, the float is OK, I agree. Sorry for the confusion...
I wrote the following XML:
```xml
<data id="#include &quot;<path_to_my_custom_header>/cust_header.h&quot;" src=""/>
<data id="float flt" expr="0.5"/>
<data id="my::custom::name::space::CustomStruct1 cust" src=""/>
```

and managed to produce the following code, which seems OK for my needs at that moment:

```cpp
  #include "<path_to_my_custom_header>/cust_header.h";
  float flt;
  my::custom::name::space::CustomStruct1 cust;
  data_model() : flt(0.5) {}
```

Thanks for confirmation!

**Comment by jp-embedded** [comment]
You are welcome. It's hard to know, when the documentation is not complete ;-)
