### ISSUE TITLE
cmake compilation error

### ISSUE THREAD

**Issue by mcirsta** [jp-embedded/scxmlcc#67]
Using the latest release, 0.8.7 the cmake compilation fails with:

CMake Error at src/test/CMakeLists.txt:6 (add_subdirectory):
  The source directory

    /home/marius/kit/scxmlcc-0.8.7/src/test/gtest

  does not contain a CMakeLists.txt file.

**Comment by jp-embedded** [comment]
You need to do a 'git submodule update --init' before when using cmake
