### ISSUE TITLE
Build breaks if gtest is found

### ISSUE THREAD

**Issue by purplefishies** [jp-embedded/scxmlcc#76]
I get the following error when building 

     cmake ..
    -- The C compiler identification is GNU 5.4.0
    -- The CXX compiler identification is GNU 5.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    ma-- Detecting CXX compile features - done
    k-- Boost version: 1.58.0
    -- Found the following Boost libraries:
    --   filesystem
    --   system
    --   program_options
    eCMake Error at src/test/CMakeLists.txt:6 (add_subdirectory):
      The source directory
    
        /home/jdamon/Downloads/scxmlcc/src/test/gtest
    
      does not contain a CMakeLists.txt file.
    
    
    -- Configuring incomplete, errors occurred!

If I run 

    touch  ../src/test/gtest/CMakeLists.txt
    nice build (master)% cmake ..
    -- Boost version: 1.58.0
    -- Found the following Boost libraries:
    --   filesystem
    --   system
    --   program_options
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/jdamon/Downloads/scxmlcc/build
    nice build (master)% make
    [  1%] Generating ../version_auto.h
    ...

Then it works

**Comment by aboseley** [comment]
@purplefishies ,  this folder get populated when you run `git submodule update --init`, see here 
[getting-started with cmake ](https://github.com/jp-embedded/scxmlcc/blob/master/doc/getting-started.md#with-cmake) 

Perhaps we should default to "disabling" unit tests so this isn't ordinarily required.

**Comment by jp-embedded** [comment]
@aboseley yes, I think that is a good idea. The unit tests is primarily of interest for developers and not so much people who just use scxmlcc

**Comment by jp-embedded** [comment]
fixed in pull request #80
