### ISSUE TITLE
Forward declaration of `sc_XXX::user_model `

### ISSUE THREAD

**Issue by sstiller** [jp-embedded/scxmlcc#85]
I have a problem with the type of `data_model::user`:
* There is (only) a forward declaration for the type `user_model` - and it can not be fully declared by a user
* To use it, an ugly  `reinterpret_cast` must be used in the constructor of the state machine

Wouldn't it be better to use `void* user`, as done in other libraries?

**Comment by sstiller** [comment]
In my case I want to provide a more complex structure, declared in a header file which does not know about the state machine.
Also this structure shall be used inside <script> and in conditions defined in the scxml.

**Comment by jp-embedded** [comment]
I am not sure I understad your case. Can you give an example?
