### ISSUE TITLE
SCXML supported elements

### ISSUE THREAD

**Issue by chrgrd** [jp-embedded/scxmlcc#9]
Hi, 

First, thank you for sxcmlcc, it is a great tool! 

I was wondering if you could document what scxml tags are currently implemented. In particular I am interested in the following  
- defining actions in the SCXML document 
- defining the user data model in SCXML
- actions during transitions 

Thanks 

Christophe

**Comment by jp-embedded** [comment]
Thanks. That is great to hear :-)

One of the next tasks is to make the documentation better. Good idea to include the implemetned/unimplemeted tags.

I will try to priorytize your needs. Unfortunately, development on scxmlcc is not so fast at the moment because of busy time at my primary job.

**Comment by jp-embedded** [comment]
Hi Christophe

defining actions and data model in scxml is now supported using cplusplus datamodel.
I have now also documented what is currently implemented.

/Jan

**Comment by chrgrd** [comment]
Hi Jan, 

Thank you very much!
