### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by pritamghanghas** [jp-embedded/scxmlcc#90]
The README mentions that "However, the generated state machine code is not covered by license." What does that mean. Does this mean that the generated code's license is up to the user? He can license the way he wants.  
or the user needs to obtain some special license if his code is not going to be open source.

**Comment by jp-embedded** [comment]
It means that the user owns his generated code. The user can use his generated code in his own software without any constrains. Only the scxmlcc tool itself is covered by license, which is stated in the source files and in the compiled tool (shown with 'scxmlcc -v')

**Comment by jp-embedded** [comment]
Do you have a suggestion on how to clarify this?

**Comment by sstiller** [comment]
I think, there is no action needed.
https://www.gnu.org/licenses/gpl-faq.html#WhatCaseIsOutputGPL

**Comment by jp-embedded** [comment]
Agreed. I will close it
