### ISSUE TITLE
Error on empty <raise>

### ISSUE THREAD

**Issue by sstiller** [jp-embedded/scxmlcc#93]
If empty `<raise/>` actions exist in the document, scxmlcc gives up:
`error: parse_raise: No such node (<xmlattr>)`
The same problem seems to exist for other elements, too.
See also  #62 

Example:
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<scxml xmlns="http://www.w3.org/2005/07/scxml" version="1.0" binding="early" name="raise_err" initial="State_1">
    <state id="State_1">
        <onentry>
            <raise/>
        </onentry>
    </state>
</scxml>

```

**Comment by jp-embedded** [comment]
Well, an empty raise is not allowed, since the event attribute is required. Ref https://www.w3.org/TR/scxml/#raise

So I guess it is okay that the parser aborts because it is an error in the document. But of course the error message could be better.

What do you think?

**Comment by sstiller** [comment]
You are right, I didn't check the standard.
Better messages are really useful (I needed to look into the scxmlcc source code to find the reason).
Like in #62 it happens when using the Qt Creator.

**Comment by jp-embedded** [comment]
Hmm. If qt creates such 'raise's, maybe it would be better to make it a warning instead.

**Comment by sstiller** [comment]
It can be fixed using the qt creator. A warning is not really necessary.

**Comment by jp-embedded** [comment]
fixed with a meaningful error message
