### ISSUE TITLE
Feature: user-defined log function

### ISSUE THREAD

**Issue by sstiller** [jp-embedded/scxmlcc#99]
What do you think about a logging function, defined by the user?
In my case the logs of the state machine do not fit into the logging concept. The logs  shall be sent to stderr or to a logging server depending on the current log level.
Before I add something, I'd like to know what other people think about it.
* How can a user implement it
* Should a fallback be added if the user doesn't implement it
* Other ideas?

**Comment by jp-embedded** [comment]
Well, you can relatively easy redirect clog. Example: https://github.com/jp-embedded/cpp-syslog
Would somthing like that be helpful?

**Comment by ringlej** [comment]
Yup. What @jp-embedded shows in his cpp-syslog is exactly the technique I use.
Here is an example of one that I've used to log the time delta since the previous log message emitted by the same thread:
https://gist.github.com/ringlej/f17ae5507d96a186c26e9113ee16f12b

**Comment by sstiller** [comment]
I never thought about that, looks great. Thank you!
